# Generated by Django 5.2.11 on 2026-02-26 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150)),
                ('valor_imovel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entrada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa_juros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prazo_meses', models.PositiveIntegerField()),
                ('sistema', models.CharField(choices=[('SAC', 'SAC'), ('PRICE', 'PRICE')], default='SAC', max_length=10)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='novo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulação',
                'verbose_name_plural': 'Simulações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
