# Generated by Django 5.2.11 on 2026-02-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
