# Generated by Django 5.2.11 on 2026-02-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0002_add_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='share_token',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
