# Generated by Django 5.2.11 on 2026-02-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0003_add_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='dfi_mensal',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='simulation',
            name='mip_mensal',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
    ]
