# Generated by Django 5.2.11 on 2026-02-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0004_simulation_dfi_mensal_simulation_mip_mensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
