# Generated by Django 5.2.11 on 2026-02-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0005_simulation_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
